# Generated by Django 5.0.1 on 2024-08-29 08:26

import django.db.models.deletion
import django.utils.timezone
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('الله جلّ جلاله', 'الله جلّ جلاله'), ('حضرت رسول اکرم صلی الله علیه و آله', 'حضرت رسول اکرم صلی الله علیه و آله'), ('حضرت امیرالمومنین (ع)', 'حضرت امیرالمومنین (ع)'), ('حضرت فاطمه الزهرا (س)', 'حضرت فاطمه الزهرا (س)'), ('امام حسن مجتبی (ع)', 'امام حسن مجتبی (ع)'), ('امام حسین (ع)', 'امام حسین (ع)'), ('امام زین\u200cالعابدین (ع)', 'امام زین\u200cالعابدین (ع)'), ('امام محمد باقر (ع)', 'امام محمد باقر (ع)'), ('امام جعفر صادق (ع)', 'امام جعفر صادق (ع)'), ('امام موسی کاظم (ع)', 'امام موسی کاظم (ع)'), ('امام علی بن موسی الرضا (ع)', 'امام علی بن موسی الرضا (ع)'), ('امام جواد (ع)', 'امام جواد (ع)'), ('امام هادی (ع)', 'امام هادی (ع)'), ('امام حسن عسگری (ع)', 'امام حسن عسگری (ع)'), ('حضرت مهدی (ع)', 'حضرت مهدی (ع)'), ('سالروز تخریب قبور ائمه بقیع (ص)', 'سالروز تخریب قبور ائمه بقیع (ص)'), ('قرآن کریم', 'قرآن کریم'), ('حضرت زینب (س)', 'حضرت زینب (س)'), ('حضرت عباس (ع)', 'حضرت عباس (ع)'), ('حضرت رقیه (س)', 'حضرت رقیه (س)'), ('حضرت علی اکبر (ع)', 'حضرت علی اکبر (ع)'), ('حضرت علی اصغر (ع)', 'حضرت علی اصغر (ع)'), ('حضرت سکینه (ع)', 'حضرت سکینه (ع)'), ('حضرت معصومه (س)', 'حضرت معصومه (س)'), ('حضرت ام البنین (س)', 'حضرت ام البنین (س)'), ('حضرت قاسم (ع)', 'حضرت قاسم (ع)'), ('حضرت خدیجه (س)', 'حضرت خدیجه (س)'), ('حضرت ام کلثوم (س)', 'حضرت ام کلثوم (س)'), ('حضرت عبدالعظیم حسنی (ع)', 'حضرت عبدالعظیم حسنی (ع)'), ('حضرت مسلم (ع)', 'حضرت مسلم (ع)'), ('هیئت هفتگی', 'هیئت هفتگی'), ('ماه رمضان', 'ماه رمضان'), ('ادعیه', 'ادعیه'), ('اعیاد', 'اعیاد')], max_length=40, null=True)),
                ('name', models.CharField(choices=[('allah', 'الله جلّ جلاله'), ('mohammad', 'حضرت رسول اکرم صلی الله علیه و آله'), ('ali', 'حضرت امیرالمومنین (ع)'), ('fateme', 'حضرت فاطمه الزهرا (س)'), ('hasan', 'امام حسن مجتبی (ع)'), ('hosein', 'امام حسین (ع)'), ('sajad', 'امام زین\u200cالعابدین (ع)'), ('baqer', 'امام محمد باقر (ع)'), ('sadeq', 'امام جعفر صادق (ع)'), ('kazem', 'امام موسی کاظم (ع)'), ('reza', 'امام علی بن موسی الرضا (ع)'), ('javad', 'امام جواد (ع)'), ('naqi', 'امام هادی (ع)'), ('asgari', 'امام حسن عسگری (ع)'), ('mahdi', 'حضرت مهدی (ع)'), ('Destruction_of_Baqi_graves', 'سالروز تخریب قبور ائمه بقیع (ص)'), ('Holy_Quran', 'قرآن کریم'), ('zeynab', 'حضرت زینب (س)'), ('abbas', 'حضرت عباس (ع)'), ('roghaye', 'حضرت رقیه (س)'), ('ali_akbar', 'حضرت علی اکبر (ع)'), ('ali_asghar', 'حضرت علی اصغر (ع)'), ('sakine', 'حضرت سکینه (ع)'), ('masomeh', 'حضرت معصومه (س)'), ('omolbanin', 'حضرت ام البنین (س)'), ('ghasem', 'حضرت قاسم (ع)'), ('khadije', 'حضرت خدیجه (س)'), ('om_kolsom', 'حضرت ام کلثوم (س)'), ('abdol_azim_hasani', 'حضرت عبدالعظیم حسنی (ع)'), ('moslem', 'حضرت مسلم (ع)'), ('haftegi', 'هیئت هفتگی'), ('ramezan', 'ماه رمضان'), ('adiye', 'ادعیه'), ('ayad', 'اعیاد')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='generated_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenaseh', models.IntegerField(blank=True, null=True)),
                ('Price_virtual', models.DecimalField(decimal_places=0, default=300000, max_digits=7)),
                ('Price_chap', models.DecimalField(decimal_places=0, default=700000, max_digits=7)),
                ('image', models.ImageField(upload_to='static/image_with_watermark/')),
            ],
        ),
        migrations.CreateModel(
            name='history_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('shenase_banner', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tarh_hay_akhrin_monasebat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.models.RenameRandomFile('static/image_last_monasebat/'))),
            ],
        ),
        migrations.CreateModel(
            name='imagesTowMadah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('shenaseh', models.IntegerField(blank=True, default=home.models.generate, null=True)),
                ('image_asli', models.ImageField(upload_to=home.models.RenameFile('static/images_asli/'))),
                ('image_kham', models.ImageField(upload_to=home.models.RenameFile('static/images_kham/'))),
                ('leye_baz', models.FileField(blank=True, null=True, upload_to=home.models.RenameFile('static/layebaz/'))),
                ('Price_virtual', models.DecimalField(decimal_places=0, default=300000, max_digits=7)),
                ('Price_chap', models.DecimalField(decimal_places=0, default=700000, max_digits=7)),
                ('Scale_x_y', models.CharField(choices=[('center', 'center'), ('right', 'right')], default='center', max_length=7)),
                ('x_madah', models.CharField(default='center', max_length=10)),
                ('y_madah', models.IntegerField(default=10)),
                ('font_size_madah', models.IntegerField(default=10)),
                ('default_hex_color_madah', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_madah', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_madah2', models.CharField(default='center', max_length=10)),
                ('y_madah2', models.IntegerField(default=10)),
                ('font_size_madah2', models.IntegerField(default=10)),
                ('default_hex_color_madah2', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_madah2', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_sokhanran', models.CharField(default='center', max_length=10)),
                ('y_sokhanran', models.IntegerField(default=10)),
                ('font_size_sokhanran', models.IntegerField(default=10)),
                ('default_hex_color_sokhanran', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_sokhanran', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_address', models.CharField(default='center', max_length=10)),
                ('y_address', models.IntegerField()),
                ('font_size_addres', models.IntegerField(default=10)),
                ('default_hex_color_address', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_address', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_zamn', models.CharField(default='center', max_length=10)),
                ('y_zaman', models.IntegerField()),
                ('font_size_zaman', models.IntegerField(default=10)),
                ('default_hex_color_zaman', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_zaman', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_esmheyat', models.CharField(default='center', max_length=10)),
                ('y_esmheyat', models.IntegerField()),
                ('font_size_esmheyat', models.IntegerField(default=10)),
                ('default_hex_color_esmheyat', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_esmheyat', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdT', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('shenaseh', models.IntegerField(blank=True, default=home.models.generate, null=True)),
                ('image_asli', models.ImageField(upload_to=home.models.RenameFile('static/images_asli/'))),
                ('image_kham', models.ImageField(upload_to=home.models.RenameFile('static/images_kham/'))),
                ('leye_baz', models.FileField(blank=True, null=True, upload_to=home.models.RenameFile('static/layebaz/'))),
                ('to_madah', models.BooleanField(default=False)),
                ('Price_virtual', models.DecimalField(decimal_places=0, default=300000, max_digits=7)),
                ('Price_chap', models.DecimalField(decimal_places=0, default=700000, max_digits=7)),
                ('Scale_x_y', models.CharField(choices=[('center', 'center'), ('right', 'right')], default='center', max_length=7)),
                ('x_madah', models.CharField(default='center', max_length=10)),
                ('y_madah', models.IntegerField(default=10)),
                ('font_size_madah', models.IntegerField(default=10)),
                ('default_hex_color_madah', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_madah', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_sokhanran', models.CharField(default='center', max_length=10)),
                ('y_sokhanran', models.IntegerField(default=10)),
                ('font_size_sokhanran', models.IntegerField(default=10)),
                ('default_hex_color_sokhanran', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_sokhanran', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_address', models.CharField(default='center', max_length=10)),
                ('y_address', models.IntegerField()),
                ('font_size_addres', models.IntegerField(default=10)),
                ('default_hex_color_address', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_address', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_zamn', models.CharField(default='center', max_length=10)),
                ('y_zaman', models.IntegerField()),
                ('font_size_zaman', models.IntegerField(default=10)),
                ('default_hex_color_zaman', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_zaman', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('x_esmheyat', models.CharField(default='center', max_length=10)),
                ('y_esmheyat', models.IntegerField()),
                ('font_size_esmheyat', models.IntegerField(default=10)),
                ('default_hex_color_esmheyat', models.CharField(default='#ffffff', max_length=8)),
                ('font_name_esmheyat', models.CharField(choices=[('B titr', 'B titr'), ('yakan_bold', 'yakan_bakh'), ('Lyon', 'Lyon'), ('Almas', 'Almas'), ('Mj_Sayeh', 'Mj_Sayeh')], default='B titr', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('two_madah_True', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.imagestowmadah')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeTwoMadah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.imagestowmadah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='monasebat_hay_bazdik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=30)),
                ('mah_monasebat', models.CharField(default='-', max_length=50)),
                ('roz_monasebat', models.CharField(default='-', max_length=50)),
                ('monasebat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monasebat_hay_bazdik', to='home.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='imagestowmadah',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.subcategory'),
        ),
        migrations.AddField(
            model_name='images',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsTwo', to='home.subcategory'),
        ),
    ]
