# Generated by Django 5.0.1 on 2024-08-29 08:37

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarh_hay_akhrin_monasebat',
            name='image',
            field=models.ImageField(upload_to=home.models.RenameRandomFile('image_last_monasebat/')),
        ),
    ]
