# Generated by Django 5.0.1 on 2024-08-29 08:45

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tarh_hay_akhrin_monasebat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='vitrin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.models.RenameRandomFile('vitrin/'))),
            ],
        ),
    ]
