# Generated by Django 5.0.1 on 2024-08-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vitrin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vitrin',
            new_name='Vitrin_home',
        ),
    ]
