# Generated by Django 5.0.1 on 2024-09-03 09:51

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_vitrin_vitrin_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_image',
            name='image',
            field=models.ImageField(upload_to='media/image_with_watermark/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_asli',
            field=models.ImageField(upload_to=home.models.RenameFile('media/images_asli/')),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_kham',
            field=models.ImageField(upload_to=home.models.RenameFile('media/images_kham/')),
        ),
        migrations.AlterField(
            model_name='images',
            name='leye_baz',
            field=models.FileField(blank=True, null=True, upload_to=home.models.RenameFile('media/layebaz/')),
        ),
        migrations.AlterField(
            model_name='imagestowmadah',
            name='image_asli',
            field=models.ImageField(upload_to=home.models.RenameFile('media/images_asli/')),
        ),
        migrations.AlterField(
            model_name='imagestowmadah',
            name='image_kham',
            field=models.ImageField(upload_to=home.models.RenameFile('media/images_kham/')),
        ),
        migrations.AlterField(
            model_name='imagestowmadah',
            name='leye_baz',
            field=models.FileField(blank=True, null=True, upload_to=home.models.RenameFile('media/layebaz/')),
        ),
    ]
