# Generated by Django 5.0.1 on 2024-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_generated_image_image_alter_images_image_asli_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='x_zamn',
            new_name='x_zaman',
        ),
        migrations.RenameField(
            model_name='imagestowmadah',
            old_name='x_zamn',
            new_name='x_zaman',
        ),
        migrations.RemoveField(
            model_name='images',
            name='Scale_x_y',
        ),
        migrations.RemoveField(
            model_name='imagestowmadah',
            name='Scale_x_y',
        ),
        migrations.AddField(
            model_name='images',
            name='Scale_x_y_address',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='images',
            name='Scale_x_y_esmheyat',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='images',
            name='Scale_x_y_madah',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='images',
            name='Scale_x_y_sokhanran',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='images',
            name='Scale_x_y_zaman',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='imagestowmadah',
            name='Scale_x_y_address',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='imagestowmadah',
            name='Scale_x_y_esmheyat',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='imagestowmadah',
            name='Scale_x_y_madah',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='imagestowmadah',
            name='Scale_x_y_madah2',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='imagestowmadah',
            name='Scale_x_y_sokhanran',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
        migrations.AddField(
            model_name='imagestowmadah',
            name='Scale_x_y_zaman',
            field=models.CharField(choices=[('center', 'center'), ('right', 'right'), ('left', 'left')], default='center', max_length=7),
        ),
    ]
