# Generated by Django 5.0.1 on 2024-09-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_created_images_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrin_home',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.subcategory'),
        ),
    ]
